global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    network: mythicpvp

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: mythiccord
    metrics_path: /metrics
    static_configs:
      - targets: ["mythiccord:8080"]
        labels: { component: proxy }

  - job_name: spacetimedb
    metrics_path: /metrics
    static_configs:
      - targets: ["spacetimedb:3000"]
        labels: { component: database }

  - job_name: folia
    metrics_path: /metrics
    static_configs:
      - targets: ["hub:9100", "skyblock-1:9100"]
        labels: { component: gameserver }

  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]
        labels: { component: api }
