name: MythicCore
version: ${project.version}
main: net.mythicpvp.core.MythicCorePlugin
api-version: '1.21'
folia-supported: true
depend:
  - MythicSuite
softdepend:
  - PlaceholderAPI
authors:
  - MythicPvP
