server-port=25565
online-mode=false
enforce-secure-profile=false
prevent-proxy-connections=false
network-compression-threshold=256
view-distance=8
simulation-distance=6
max-players=200
spawn-protection=0
allow-flight=true
enable-command-block=false
sync-chunk-writes=false
use-native-transport=true
enable-status=true
hide-online-players=false
white-list=false
broadcast-rcon-to-ops=false
enable-rcon=false
motd=MythicPvP
