port=24454
bind_address=
voice_host=
max_voice_distance=48.0
crouch_distance_multiplier=1.0
whisper_distance_multiplier=0.5
broadcast_range=-1.0
allow_recording=true
keep_alive=1000
groups_enabled=true
open_groups=true
